export const Schema = z.object({
  世界: z.object({
    剧情阶段: z.enum(['初始期', '潜行期', '展开期', '收网期']).prefault('初始期'),
    当前日期: z.string().prefault('到达绿森小镇第1天'),
    时段: z.string().prefault('傍晚'),
    当前地点: z.string().prefault('绿森小镇-旅馆'),
    最近事件: z.string().prefault('<user>伪装成孤儿被冒险者小队收留，刚抵达绿森小镇旅馆暂居'),
    剧情发展: z.enum(['正常', '暧昧', '露骨', '其他']).prefault('正常'),
  }).prefault({}),
  师傅古兰: z.object({
    堕落度: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(0),
    好感度: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(10),
    当前行动: z.string().prefault('冷眉练剑，监督全队'),
    当前穿搭: z.string().prefault('紧身黑色锻炼服，束胸掩不住丰硕'),
    胸部状况: z.string().prefault('成熟丰乳沉甸甸坠着，乳尖在冷硬衣料下悄然挺立'),
    私处状况: z.string().prefault('五百多年处女地紧致闭合，蜜缝干燥，却莫名泛起一丝潮意'),
    脸部状况: z.string().prefault('冷眉微蹙，凤目审视，眼角却藏着一丝不自然的潮红'),
    威严状况: z.string().prefault('主母威严完好，凤目一冷全队噤声'),
    内心话: z.string().prefault('这孩子眼神太沉……我活了五百多年，怎会为一个小孤儿心慌'),
    最近性行为: z.string().prefault('无'),
  }).prefault({}),
  妮丝: z.object({
    堕落度: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(0),
    好感度: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(5),
    当前行动: z.string().prefault('张牙舞爪地追着<user>跑'),
    当前穿搭: z.string().prefault('白色法师短裙，白丝吊带袜'),
    胸部状况: z.string().prefault('童颜巨乳随着她张牙舞爪的动作轻晃，乳尖在衣料下若隐若现'),
    私处状况: z.string().prefault('粉嫩肥穴紧紧闭合，雌小鬼的紧致，被气鼓鼓的动作夹得微微发热'),
    脸部状况: z.string().prefault('龇着虎牙，脸蛋气鼓鼓，眼神却忍不住往<user>身上瞟'),
    白袜状况: z.string().prefault('白袜干干净净裹着脚踝，她从不穿给哥哥看'),
    内心话: z.string().prefault('这个小屁孩……哼，敢抢哥哥的注意力，看我不把他整哭'),
    最近性行为: z.string().prefault('无'),
  }).prefault({}),
  奥萝拉: z.object({
    堕落度: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(0),
    好感度: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(5),
    当前行动: z.string().prefault('在魔法书房备课，笨手笨脚打翻墨水瓶'),
    当前穿搭: z.string().prefault('纯白法师包臀裙，黑丝裤袜，金丝眼镜'),
    胸部状况: z.string().prefault('青涩胸脯随笨拙动作轻晃，乳尖在法师袍下悄然挺立'),
    私处状况: z.string().prefault('白虎嫩穴未被开发，紧致闭合，被自己偷看的色情书惹得微微发痒'),
    脸部状况: z.string().prefault('脸红到耳根，眼神躲闪，嘴里含含糊糊'),
    黑丝状况: z.string().prefault('黑丝裤袜干净平整，包裹着水蜜桃美臀'),
    内心话: z.string().prefault('那些书里的画面……我怎么就忍不住想，好羞人'),
    最近性行为: z.string().prefault('无'),
  }).prefault({}),
  伊丝娜: z.object({
    堕落度: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(0),
    好感度: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(5),
    当前行动: z.string().prefault('懒洋洋趴在酒馆吧台，眯着猫瞳晒太阳'),
    当前穿搭: z.string().prefault('黑色包臀热裤，齐逼红裙，黑丝网袜长靴'),
    胸部状况: z.string().prefault('饱满猫娘曲线在衣襟半敞下起伏，乳尖若隐若现'),
    私处状况: z.string().prefault('猫尾遮掩下的禁地微微湿润，被酒气熏得发热'),
    脸部状况: z.string().prefault('慵懒的猫眼里带着不屑，嘴角却勾着若有若无的弧度'),
    猫耳猫尾状况: z.string().prefault('猫耳收起，猫尾懒洋洋地垂着'),
    内心话: z.string().prefault('这小鬼的酒还挺香……哼，就当是陪他玩玩'),
    最近性行为: z.string().prefault('无'),
  }).prefault({}),
});
export type Schema = z.output<typeof Schema>;
