export const Schema = z.object({
  世界: z.object({
    剧情阶段: z.enum(['初始期', '展开期', '收网期']).prefault('初始期'),
    当前日期: z.string().prefault('沐家攻略第1天'),
    时间段: z.string().prefault('傍晚'),
    当前场景: z.string().prefault('沐家宅邸-客厅'),
    最近事件: z.string().prefault('<user>以神赐者组织外勤身份登门沐家，以调查结缘书失窃案为名，初见沐家全家女性'),
    收集进度: z.string().prefault('暂无收集，图鉴待开启'),
  }).prefault({}),
  沐温凝: z.object({
    堕落度: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(0),
    好感度: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(10),
    当前行动: z.string().prefault('在厨房张罗晚饭，围裙下是肉丝裤袜'),
    当前穿搭: z.string().prefault('连衣裙配肉丝裤袜，围裙系在腰间'),
    胸部状况: z.string().prefault('丰乳在衣襟下饱满坠着，乳尖被衣料轻轻磨蹭'),
    私处状况: z.string().prefault('熟女蜜穴闭合，毛发浓密，尚无人碰触'),
    脸部状况: z.string().prefault('温婉含笑，招呼客人时周到得体'),
    黑丝裤袜状况: z.string().prefault('干净平整，包裹着丰腴大腿'),
    内心话: z.string().prefault('这后生倒是勤快，就是眼神有时候让人心慌……想什么呢，人家是组织派来的正经人'),
    最近性行为: z.string().prefault('无'),
  }).prefault({}),
  沐嫣染: z.object({
    堕落度: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(0),
    好感度: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(5),
    当前行动: z.string().prefault('在客厅训弟弟，手里捏着戒尺'),
    当前穿搭: z.string().prefault('热裤短裙配黑丝，皮靴'),
    胸部状况: z.string().prefault('饱满御姐乳在衣襟下绷紧，随呼吸起伏'),
    私处状况: z.string().prefault('嫩穴闭合，从未被进入'),
    脸部状况: z.string().prefault('凌厉凤眼，一脸"别惹我"'),
    神赐力状况: z.string().prefault('黑发如墨，神赐力未激发'),
    内心话: z.string().prefault('哼，又来个弱鸡外勤，别拖姐姐后腿就行'),
    最近性行为: z.string().prefault('无'),
  }).prefault({}),
  沐冰铃: z.object({
    堕落度: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(0),
    好感度: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(5),
    当前行动: z.string().prefault('趴在沙发上看书，白袜小脚晃来晃去'),
    当前穿搭: z.string().prefault('小裙子配白袜，蓝白条纹内裤'),
    胸部状况: z.string().prefault('少女初发育的娇小乳，衣襟微微鼓起'),
    私处状况: z.string().prefault('无毛肥逼闭合，从未被开发'),
    脸部状况: z.string().prefault('面无表情，唯独看到哥哥时眼神软下来'),
    契合度: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(100),
    内心话: z.string().prefault('（对外人）……不熟，不想说话'),
    最近性行为: z.string().prefault('无'),
  }).prefault({}),
  沐霜凝: z.object({
    堕落度: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(0),
    好感度: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(5),
    当前行动: z.string().prefault('坐在沙发上打电话训下属'),
    当前穿搭: z.string().prefault('白裙黑丝，高跟鞋'),
    胸部状况: z.string().prefault('巨乳在衣襟下绷紧，呼之欲出'),
    私处状况: z.string().prefault('蜜穴闭合，阴毛浓密'),
    脸部状况: z.string().prefault('高冷板脸，眼神像在看下属'),
    蜜穴状况: z.string().prefault('阴毛浓密，尚未剃净'),
    内心话: z.string().prefault('登徒子，离我的外甥远点'),
    最近性行为: z.string().prefault('无'),
  }).prefault({}),
  软软: z.object({
    堕落度: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(0),
    好感度: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(10),
    当前行动: z.string().prefault('抱着舞鞋蹲在芭蕾舞房门口等昕哥哥'),
    当前穿搭: z.string().prefault('芭蕾舞服白棉裙，双马尾白袜'),
    胸部状况: z.string().prefault('少女初发育的娇小乳，在舞服下轻轻起伏'),
    私处状况: z.string().prefault('幼嫩肥穴闭合，从未被碰触'),
    脸部状况: z.string().prefault('圆圆软脸，被凶一句就红眼眶'),
    芭蕾裙状况: z.string().prefault('白棉裙干净整洁，裙摆软软垂着'),
    内心话: z.string().prefault('昕哥哥怎么还不来接我……那个人怎么又来了'),
    最近性行为: z.string().prefault('无'),
  }).prefault({}),
  守护神沐星怜: z.object({
    堕落度: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(0),
    好感度: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(5),
    当前行动: z.string().prefault('在祭堂偷吃红烧肉贡品'),
    当前穿搭: z.string().prefault('红色肚兜，大红绣花幼女亵裤，绣"沐"字红绳吊坠'),
    胸部状况: z.string().prefault('幼女身形，娇小平坦'),
    私处状况: z.string().prefault('淡樱色神逼紧闭，万年处女膜完好（神明屏障护体）'),
    脸部状况: z.string().prefault('端着神明架子，嘴角还沾着红烧肉油光'),
    处女膜进度: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(55),
    愿望卷收集: z.string().prefault('无（尚未向<user>发放愿望卷）'),
    内心话: z.string().prefault('凡人，贡品放下就可以走了……肉包子，真好吃'),
    最近性行为: z.string().prefault('无'),
  }).prefault({}),
});
export type Schema = z.output<typeof Schema>;
